import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LandingItems from "./components/landing/landingItems";
import { siteTitle } from "./components/layout/layout";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>{siteTitle}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://fonts.googleapis.com/css2?family=Lato&family=Quicksand&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<LandingItems />
			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer">
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
